# Generated by Django 3.2.7 on 2021-09-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.TextField(verbose_name='Текст задачи')),
                ('task_complete', models.BooleanField(verbose_name='Состояние')),
            ],
        ),
    ]
